### PR TITLE
Add Update Email Full Content endpoint, and add new params to Update Email endpoint

### PR DESCRIPTION
**Pull request by aeromusek**

### CODE REVIEW

**Comment by aeromusek** [comment]
@jepcastelein I didn’t add a description here because it seemed like a pretty straightforward and self-explanatory update, but let me know if there’s something specific you like to see in these PRs! 👍

**Comment by jepcastelein** [comment]
Thanks @aeromusek I'm a little tied up with a project right now but I'll merge as soon as I have a chance

**Review by jepcastelein — APPROVED** [review]

**Comment by jepcastelein** [comment]
@aeromusek sorry for the delay, this should now be available via `pip install --upgrade marketorestpython`

**Comment by aeromusek** [comment]
Ahhhh brilliant! That’s awesome — works like a charm now.

**Pull request merged**
